

import {
  LayoutDashboard,
  BarChart2,
  School,
  Mail,
  BookOpen,
  Bot,
  Store,
  Settings,
  PanelLeft,
  PanelRight,
  Search,
  X,
  Clock,
  Newspaper,
  MessageSquare,
  Cloud,
  Palette,
  Code2,
  FileText,
  Clapperboard,
  Gamepad2,
  HeartPulse,
  Bike,
  Music,
  Tv,
  Camera,
  ChevronRight,
  ChevronLeft,
  Users,
  User,
  Shield,
  Palette as BrandingIcon, // Alias for clarity
  BarChartHorizontal,
  DollarSign,
  Briefcase,
  GraduationCap,
  BookCopy,
  Library,
  Lightbulb,
  Cpu,
  ShoppingBag,
  Truck,
  SendHorizontal,
  ClipboardCheck,
  GitBranch,
  Sparkles,
  BookHeart,
  Goal,
  PenSquare,
  ScanLine,
  Siren,
  Wand2,
  Paintbrush,
  Activity,
  Scale,
  BrainCircuit,
  Megaphone,
  TrendingUp,
  Award,
  Share2,
  BarChart3,
  FileCog,
  Smile,
  MessageSquare as ParentComms,
  // Added to fix errors
  Image,
  Upload,
  Save,
  UserPlus,
  View,
  Trash2,
  Smartphone,
  PlusCircle,
  Plus,
  Edit,
  MoreVertical,
  Check,
  Eye,
  Download,
  PlayCircle,
  TrendingDown,
  CheckCircle,
  MousePointer2,
  Type as TypeIcon,
  StickyNote,
  Undo,
  Redo,
  Facebook,
  Twitter,
  // Added for new features
  Pin,
  PinOff,
  AlertTriangle,
  CalendarDays,
  History,
  Undo2,
  Home,
  Printer,
  MapPin,
  Instagram,
  Bell,
  // Icons for Studio
  Video as VideoIcon,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  File as FileIcon,
  Sheet,
  Presentation as PresentationIcon,
  RectangleHorizontal,
  Circle,
  Diamond,
  ArrowRight,
  Minus,
  // Icons for Settings
  Puzzle,
  CreditCard,
  Globe,
  UserCog,
  Wallet,
  KeyRound,
  Webhook,
  BookLock,
  // Icons for Knowledge Base
  Calculator,
  FlaskConical,
  Filter,
  Bookmark,
  Computer,
  // Icons for Marketplace
  ShoppingCart,
  Ticket,
  Package,
  Tag,
  Heart,
  Shirt,
  Laptop,
  List,
  MinusCircle,
  Tablet,
  // Added for Analytics module errors
  PieChart,
  BarChart,
  LogIn,
  LogOut,
  // New icons for Hobbies dashboard
  Mountain,
  Leaf,
  Database,
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Analytics: BarChart2,
  School: School,
  Communications: Mail,
  KnowledgeBase: BookOpen,
  ConciergeAI: Bot,
  Marketplace: Store,
  SystemSettings: Settings,
  ToggleSidebar: PanelLeft,
  ToggleSidebarRight: PanelRight,
  Search: Search,
  Close: X,
  Time: Clock,
  News: Newspaper,
  Chat: MessageSquare,
  Cloud: Cloud,
  Canva: Palette,
  Coder: Code2,
  Office: FileText,
  Video: Clapperboard,
  Gamification: Gamepad2,
  Lifestyle: HeartPulse,
  Hobbies: Bike,
  Media: Music,
  Tv: Tv,
  Studio: Camera,
  ChevronRight,
  ChevronLeft,
  Users,
  User,
  Security: Shield,
  Branding: BrandingIcon, // Alias for clarity
  Overview: BarChartHorizontal,
  Finance: DollarSign,
  Marketing: TrendingUp, // Added to fix errors
  Briefcase,
  Students: GraduationCap,
  Administration: Users,
  Curriculum: BookCopy,
  Library: Library,
  SystemPrompts: Lightbulb,
  UsageAnalytics: Cpu,
  Storefront: ShoppingBag,
  Orders: Truck,
  Send: SendHorizontal,
  ClipboardCheck,

  // New Icons for School Hub Features
  LearningPath: GitBranch,
  AIHelper: Sparkles,
  GrowthJournal: BookHeart,
  Goal,
  CommunityHubs: Users, // Reusing
  DailyDigest: Newspaper, // Reusing
  WellnessAlerts: HeartPulse, // Reusing
  HomeworkSupport: PenSquare,
  AIGrading: ScanLine,
  GapDetector: Siren,
  ContentGen: Wand2,
  CollabBoard: Paintbrush,
  HealthMonitor: Activity,
  LoadBalancer: Scale,
  PredictiveAI: BrainCircuit,
  CrisisHub: Megaphone,
  PredictiveBudgeting: TrendingUp,
  GrantManagement: Award,
  SocialMediaAI: Share2,
  EnrollmentForecasting: BarChart3,
  PolicyGenerator: FileCog,
  FeedbackAI: Smile,
  ParentComms,

  // Icons that were used directly but only aliased before
  Activity,
  Megaphone,
  Wand2,
  PenSquare,
  Siren,
  BrainCircuit,
  TrendingUp,
  BookOpen,
  ScanLine,

  // Truly new icons to fix errors
  Image,
  Upload,
  Save,
  UserPlus,
  View,
  Trash2,
  Smartphone,
  PlusCircle,
  Plus,
  Edit,
  MoreVertical,
  Check,
  Eye,
  Download,
  PlayCircle,
  TrendingDown,
  CheckCircle,
  MousePointer2,
  Type: TypeIcon,
  StickyNote,
  Undo,
  Redo,
  Facebook,
  Twitter,
  Award,
  Shield,
  Cpu,
  // Fixed: Add missing icons for direct access in Marketplace
  GraduationCap,
  Heart,
  Sparkles,
  Smile,

  // New Icons for enhancements
  Pin,
  PinOff,
  AlertTriangle,
  CalendarDays,
  Book: BookCopy, // Alias for category icon
  History,
  Revert: Undo2,
  Home,
  Printer,
  MapPin,
  Instagram,
  Bell,

  // Window management
  Minimize: Minus,

  // Icons for Studio
  Design: Palette,
  VideoL1: VideoIcon,
  CoderL1: Code2,
  OfficeL1: FileText,
  Word: FileIcon,
  Excel: Sheet,
  PowerPoint: PresentationIcon,
  Diagram: Share2,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Rectangle: RectangleHorizontal,
  Circle,
  Diamond,
  ArrowRight,

  // Icons for Settings
  Puzzle,
  CreditCard,
  Globe,
  UserCog,
  Wallet,
  KeyRound,
  Webhook,
  BookLock,

  // Icons for Knowledge Base
  Calculator,
  FlaskConical,
  Filter,
  Bookmark,
  Computer,
  
  // Icons for Marketplace
  ShoppingCart,
  Ticket,
  Events: Ticket, // Alias
  Services: Briefcase,
  Package,
  Deals: Tag,
  Apparel: Shirt,
  Books: BookCopy,
  Tech: Laptop,
  GiftShop: Heart,
  MyOrders: List,
  MyListings: Tag,
  PaymentSettings: Wallet,
  MinusCircle,
  Tablet,
  Laptop,

  // Icons for Hobbies
  Creative: Paintbrush,
  Sports: Bike,
  Gaming: Gamepad2,
  Collecting: Package,
  Outdoors: Mountain,
  ArtGallery: Image,
  MusicStudio: Music,
  WritingDesk: PenSquare,
  ActivityLog: Activity,
  GoalTracker: Goal,
  TeamHub: Users,
  GameLibrary: Library,
  SessionLogger: History,
  BoardGameNights: CalendarDays,
  CollectionManager: Database,
  Wishlist: Heart,
  TrailFinder: MapPin,
  GardenPlanner: Leaf,


  // Add direct access to icons to fix errors
  Store,
  Settings,
  FileText,
  Music,
  BookCopy,
  PieChart,
  BarChart,
  BarChart2,
  BarChart3,
  List,
  LogIn,
  LogOut,
};
